# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'validacpf.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 247)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 10, 338, 69))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: red;")
        self.label_4.setObjectName("label_4")
        self.btnValidaCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCPF.setGeometry(QtCore.QRect(450, 80, 111, 41))
        self.btnValidaCPF.setObjectName("btnValidaCPF")
        self.lblGeraCPF = QtWidgets.QPushButton(self.centralwidget)
        self.lblGeraCPF.setGeometry(QtCore.QRect(450, 130, 111, 41))
        self.lblGeraCPF.setObjectName("lblGeraCPF")
        self.inputValidaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCPF.setGeometry(QtCore.QRect(103, 85, 341, 31))
        self.inputValidaCPF.setObjectName("inputValidaCPF")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.inputRetorno = QtWidgets.QLineEdit(self.centralwidget)
        self.inputRetorno.setGeometry(QtCore.QRect(0, 180, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.inputRetorno.setFont(font)
        self.inputRetorno.setReadOnly(True)
        self.inputRetorno.setObjectName("inputRetorno")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Válidar CPF:"))
        self.label_4.setText(_translate("MainWindow", "Válidador de CPF"))
        self.btnValidaCPF.setText(_translate("MainWindow", "VALIDAR"))
        self.lblGeraCPF.setText(_translate("MainWindow", "GERAR"))
        self.label_2.setText(_translate("MainWindow", "Gerar CPF:"))
